### ISSUE TITLE
`helm repo up` not working with helm-gcs

### ISSUE THREAD

**Issue by Talador12** [hayorov/helm-gcs#68]
Example:
```
→ helm gcs push staging-model-template-0-1-0.tgz bi-staging --force

→ helm repo up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bi-staging" chart repository
Update Complete. ⎈Happy Helming!⎈

→ helm fetch bi-staging/staging-model-template-0-1-0
Error: chart "staging-model-template-0-1-0" matching  not found in bi-staging index. (try 'helm repo update'): no chart name found

→ helm gcs push staging-model-template-0-1-0.tgz bi-staging
Error: chart staging-model-template-0-1-0 already indexed. Use --force to still upload the chart

→ helm search repo  bi-staging
No results found
```

See - it is indexed when you try to push, but it is not when you try to fetch/update/search.

When viewing the GCS bucket, the `.tgz` is there, along with an `index.yaml` as follows:

Note: Just for privacy on a public post, I removed the `digest` variable and changed the bucket name to `gs://HIDDEN`. The information is correct on the real bucket

```
apiVersion: v1
entries:
  staging-model-template:
  - apiVersion: v2
    appVersion: 0-1-0
    created: "2020-09-29T12:14:32.763916-05:00"
    description: Model description goes here
    icon: https://i.imgur.com/lc9OKZr.png
    name: staging-model-template
    type: application
    urls:
    - gs://HIDDEN/staging-model-template-0-1-0.tgz
    version: 0-1-0
generated: "2020-09-29T12:14:32.763918-05:00"
```

Is this a caching issue related to #44 ? What is happening to cause this? How would it be resolved?
